apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: app-ns
spec:
  type: LoadBalancer
  selector:
    app: app-dp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000